#pragma once

#include <cstddef>

enum class ResponseKind {
    yes,
    no,
    maybe,
    ominous,
};

struct Response {
    ResponseKind kind;
    const char* text;
};

constexpr Response kResponses[] = {
    {ResponseKind::yes, "YES. EVEN A BROKEN CLOCK GETS TWO WINS A DAY."},
    {ResponseKind::yes, "YES. TRY NOT TO LOOK SO SURPRISED BY COMPETENCE."},
    {ResponseKind::yes, "YES. THE UNIVERSE HAS CLEARLY LOWERED ITS STANDARDS."},
    {ResponseKind::yes, "YES. ENJOY THIS BRIEF ADMINISTRATIVE ERROR."},
    {ResponseKind::yes, "YES. AGAINST REASON, EVIDENCE, AND BETTER JUDGMENT."},
    {ResponseKind::yes, "YES. SOMEONE UPSTAIRS HAS A VERY STRANGE SENSE OF HUMOUR."},
    {ResponseKind::yes, "YES. DO NOT MAKE IT WEIRD. YOU WILL MAKE IT WEIRD."},
    {ResponseKind::yes, "YES. APPARENTLY CONSEQUENCES HAVE TAKEN THE DAY OFF."},
    {ResponseKind::yes, "YES. THIS IS YOUR PEAK. TAKE A PHOTO."},
    {ResponseKind::yes, "YES. THE BAR WAS LOW, BUT YOU CLEARED IT."},
    {ResponseKind::yes, "YES. FATE MISREAD THE FORM. KEEP QUIET."},
    {ResponseKind::yes, "YES. YOUR UNDESERVED CONFIDENCE FINALLY PAID RENT."},
    {ResponseKind::yes, "YES. THIS WAS NOT THE PLAN. IT IS THE PLAN NOW."},
    {ResponseKind::yes, "YES. TRY TO ACT LIKE YOU MEANT THAT."},
    {ResponseKind::yes, "YES. THE OBSTACLES GOT BORED AND WANDERED OFF."},
    {ResponseKind::yes, "YES. DO NOT INVESTIGATE WHY. JUST LEAVE."},
    {ResponseKind::yes, "YES. COMPETENCE MADE A RARE HOUSE CALL."},
    {ResponseKind::yes, "YES. YOUR LUCK HAS A LIMITED WARRANTY."},
    {ResponseKind::yes, "YES. NOBODY IS MORE SHOCKED THAN THE UNIVERSE."},
    {ResponseKind::yes, "YES. FILE THIS UNDER MIRACLES, THEN LOSE THE FILE."},
    {ResponseKind::yes, "YES. THE DOOR WAS UNLOCKED. YOU STILL HESITATED."},
    {ResponseKind::yes, "YES. ENJOY IT BEFORE THE PAPERWORK ARRIVES."},
    {ResponseKind::yes, "YES. EVEN THE SCEPTICS ARE ANNOYED ABOUT THIS."},
    {ResponseKind::yes, "YES. YOU MAY PROCEED. SUSPICIOUSLY."},

    {ResponseKind::no, "NO. I CHECKED TWICE. THE SECOND TIME WAS FOR COMEDY."},
    {ResponseKind::no, "NO. EVEN YOUR PLAN B HAS STARTED LOOKING FOR WORK."},
    {ResponseKind::no, "NO. THE UNIVERSE SAW YOUR EFFORT AND PRESSED MUTE."},
    {ResponseKind::no, "NO. BUT PLEASE CONTINUE. FAILURE NEEDS CONTENT."},
    {ResponseKind::no, "NO. YOUR OPTIMISM REMAINS YOUR LEAST CONVINCING TRAIT."},
    {ResponseKind::no, "NO. THE ODDS LEFT WITHOUT SAYING GOODBYE."},
    {ResponseKind::no, "NO. THAT IDEA HAS THE STRUCTURAL INTEGRITY OF SOUP."},
    {ResponseKind::no, "NO. REALITY HAS FILED A FORMAL COMPLAINT."},
    {ResponseKind::no, "NO. YOU HAVE CONFUSED A WHIM WITH A STRATEGY AGAIN."},
    {ResponseKind::no, "NO. HOPE WAS CONSULTED. HOPE LAUGHED."},
    {ResponseKind::no, "NO. THIS COULD HAVE BEEN AN EMAIL YOU NEVER SENT."},
    {ResponseKind::no, "NO. YOUR FUTURE SELF ALREADY BLAMES YOU."},
    {ResponseKind::no, "NO. AND THE ECHO AGREED, WHICH WAS RUDE."},
    {ResponseKind::no, "NO. THAT PLAN HAS ALREADY UNIONISED AGAINST YOU."},
    {ResponseKind::no, "NO. I WOULD EXPLAIN, BUT YOU WOULD ARGUE."},
    {ResponseKind::no, "NO. THE FINE PRINT READ ITSELF AND WINCED."},
    {ResponseKind::no, "NO. SAVE YOUR ENERGY FOR THE APOLOGY."},
    {ResponseKind::no, "NO. THIS IS A NO WITH A VIEW."},
    {ResponseKind::no, "NO. YOUR CONFIDENCE DID NOT SURVIVE PEER REVIEW."},
    {ResponseKind::no, "NO. THE TIMELINE REVIEWED YOUR DRAFT AND DECLINED."},
    {ResponseKind::no, "NO. PLEASE STOP NEGOTIATING WITH PHYSICS."},
    {ResponseKind::no, "NO. EVEN THE BACKUP PLAN PACKED A BAG."},
    {ResponseKind::no, "NO. I RAN THE NUMBERS. THEY RAN AWAY."},
    {ResponseKind::no, "NO. CONSIDER THIS A PUBLIC SERVICE."},

    {ResponseKind::maybe, "MAYBE. WHICH IS MYSTIC FOR: I CANNOT BE BOTHERED."},
    {ResponseKind::maybe, "MAYBE. LOWER YOUR EXPECTATIONS UNTIL THEY STOP SQUEAKING."},
    {ResponseKind::maybe, "MAYBE. THE DISASTER IS STILL IN BETA."},
    {ResponseKind::maybe, "MAYBE. ASK AGAIN AFTER DEVELOPING A BETTER QUESTION."},
    {ResponseKind::maybe, "MAYBE. FATE IS PRETENDING NOT TO SEE YOUR MESSAGE."},
    {ResponseKind::maybe, "MAYBE. YOUR PLAN HAS BOTH COURAGE AND NO SUPERVISION."},
    {ResponseKind::maybe, "MAYBE. THE COMMITTEE OF BAD IDEAS IS STILL VOTING."},
    {ResponseKind::maybe, "MAYBE. CONFIDENCE IS DOING ALL THE WORK HERE."},
    {ResponseKind::maybe, "MAYBE. RESULTS MAY VARY. YOURS USUALLY DO."},
    {ResponseKind::maybe, "MAYBE. CHAOS HAS PENCILLED YOU IN."},
    {ResponseKind::maybe, "MAYBE. YOU HAVE MISTAKEN DELAY FOR POSSIBILITY."},
    {ResponseKind::maybe, "MAYBE. PREPARE TO CALL IT A LEARNING EXPERIENCE."},
    {ResponseKind::maybe, "MAYBE. IF YOU SQUINT AND IGNORE THE SMOKE."},
    {ResponseKind::maybe, "MAYBE. THE ANSWER IS HIDING IN THE TERMS."},
    {ResponseKind::maybe, "MAYBE. SUCCESS IS IN THE BUILDING. SO IS THE FIRE EXIT."},
    {ResponseKind::maybe, "MAYBE. ASK AGAIN WHEN YOU HAVE A PLAN, NOT A VIBE."},
    {ResponseKind::maybe, "MAYBE. THE ODDS ARE OUT SOCIALISING."},
    {ResponseKind::maybe, "MAYBE. THIS COULD WORK. SO COULD APOLOGISING EARLY."},
    {ResponseKind::maybe, "MAYBE. FATE PUT YOU ON HOLD. THE MUSIC IS JUDGING YOU."},
    {ResponseKind::maybe, "MAYBE. BRING A CONTINGENCY AND A SENSE OF SHAME."},
    {ResponseKind::maybe, "MAYBE. THE SIGNS ARE MIXED. MOSTLY WARNING SIGNS."},
    {ResponseKind::maybe, "MAYBE. ONE GOOD DECISION FROM A DIFFERENT MISTAKE."},
    {ResponseKind::maybe, "MAYBE. PROBABILITY LEFT TO GET COFFEE."},
    {ResponseKind::maybe, "MAYBE. I WOULD COMMIT, BUT COMMITMENT LEFT TOO."},

    {ResponseKind::ominous, "THE MIST CLEARS. UNFORTUNATELY, YOU ARE STILL THERE."},
    {ResponseKind::ominous, "SIGNS POINT TO ANOTHER CHARACTER-BUILDING CATASTROPHE."},
    {ResponseKind::ominous, "A BOLD MOVE. HISTORY WILL USE A DIFFERENT ADJECTIVE."},
    {ResponseKind::ominous, "THE STARS DECLINE TO BE ASSOCIATED WITH THIS."},
    {ResponseKind::ominous, "PROCEED. REGRET HAS ALREADY RESERVED A TABLE."},
    {ResponseKind::ominous, "YOUR DESTINY IS BUFFERING. THE ADVERTS LOOK BETTER."},
    {ResponseKind::ominous, "MYSTIC FORCES SUGGEST YOU READ THE INSTRUCTIONS."},
    {ResponseKind::ominous, "THE VOID WHISPERS: THIS AGAIN?"},
    {ResponseKind::ominous, "OUTLOOK CLOUDY, WITH A STRONG CHANCE OF EXCUSES."},
    {ResponseKind::ominous, "I SEE GREAT THINGS. THEY APPEAR TO BELONG TO SOMEONE ELSE."},
    {ResponseKind::ominous, "DESTINY CALLED. IT WANTS MORE NOTICE NEXT TIME."},
    {ResponseKind::ominous, "THE PROPHECY WAS VAGUE, BUT THE DISAPPOINTMENT IS SPECIFIC."},
    {ResponseKind::ominous, "THE PORTENT IS CLEAR. UNFORTUNATELY, SO ARE YOU."},
    {ResponseKind::ominous, "SOMETHING WATCHES. IT IS MOSTLY EMBARRASSED."},
    {ResponseKind::ominous, "DO NOT LOOK BEHIND YOU. THE METAPHOR IS ENOUGH."},
    {ResponseKind::ominous, "A SHADOW MOVES. IT IS YOUR DEADLINE."},
    {ResponseKind::ominous, "THE OMEN ARRIVED LATE AND BLAMES THE TRAFFIC."},
    {ResponseKind::ominous, "COUNT TO TEN. THE PROBLEM IS STILL COUNTING."},
    {ResponseKind::ominous, "YOU HAVE ATTRACTED ATTENTION. NOT THE GOOD KIND."},
    {ResponseKind::ominous, "THE WHEEL TURNS. IT RUNS OVER YOUR FOOTNOTE."},
    {ResponseKind::ominous, "SILENCE. THEN A SMALL, EXPENSIVE NOISE."},
    {ResponseKind::ominous, "THIS PATH ENDS. BRING RECEIPTS."},
    {ResponseKind::ominous, "THE SPIRITS VOTED. IT WAS NOT CLOSE, AND NOT KIND."},
    {ResponseKind::ominous, "MARK THE DATE. SOMETHING AWKWARD HAS ALSO MARKED IT."},
};

constexpr std::size_t kResponseCount = sizeof(kResponses) / sizeof(kResponses[0]);
